language: go
go:
  - "1.10"

install: skip

jobs:
  include:
    - stage: test
      script:
        - CGO_ENABLED=0 go build

    - &deploy-stage
      stage: build and deploy
      sudo: required
      if: branch = master
      script:
        # build
        - >
          docker build -t write:$DOCKER_TAG         \
            --build-arg CC=$CC                        \
            --build-arg CC_PKG=$CC_PKG                \
            --build-arg CC_GOARCH=$CC_GOARCH          \
            .
      after_success:
        - echo ${DOCKER_PASSWORD} | docker login --username "rycus86" --password-stdin
        - docker tag write:${DOCKER_TAG} rycus86/write:${DOCKER_TAG}
        - docker push rycus86/write:${DOCKER_TAG}
      env:
        - DOCKER_TAG=amd64
        - BUILD_ARCH=amd64

    - <<: *deploy-stage
      env:
        - DOCKER_TAG=armhf
        - BUILD_ARCH=arm32v6
        - CC=arm-linux-gnueabihf-gcc
        - CC_PKG=gccgo-arm-linux-gnueabihf
        - CC_GOARCH=arm

    - <<: *deploy-stage
      env:
        - DOCKER_TAG=aarch64
        - BUILD_ARCH=arm64v8
        - CC=aarch64-linux-gnu-gcc
        - CC_PKG=gccgo-aarch64-linux-gnu
        - CC_GOARCH=arm64

    - stage: manifest
      sudo: required
      if: branch = master
      script:
        - echo ${DOCKER_PASSWORD} | docker login --username "rycus86" --password-stdin
        - curl -fsSL https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 > ./manifest-tool
        - chmod +x ./manifest-tool
        - ./manifest-tool push from-spec manifest.yml
